# Read the documentation: https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/doc/setup.md
fos_elastica:
    clients:
        default: { url: "%env(ELASTICSEARCH_URL)%" }
    indexes:
        articles:
            serializer:
                groups: [ elastica ]
            persistence:
                # the driver can be orm, mongodb or phpcr
                driver: orm
                model: App\Entity\Article
                provider: ~
                finder: ~
            properties:
                id: ~
                title: ~
                description: ~
                content: ~
                agent:
                    type: object
                    properties:
                        id:
                            type: keyword
                category:
                    type: object
                    properties:
                        name:
                            type: keyword

                title_vector:
                    type: dense_vector
                    dims: 1536
                    index: true
                    similarity: cosine
                content_vector:
                    type: dense_vector
                    dims: 1536
                    index: true
                    similarity: cosine
        products:
            persistence:
                # the driver can be orm, mongodb or phpcr
                driver: orm
                model: App\Entity\Product
                provider: ~
                finder: ~
            properties:
                id:
                referenceCode:
                    type: keyword
                title: ~
                description: ~
                sku:
                    type: keyword
                brand:
                    type: keyword
                image: ~
                price: ~
                user_id: ~

                title_vector:
                    type: dense_vector
                    dims: 1536
                    index: true
                    similarity: cosine
                description_vector:
                    type: dense_vector
                    dims: 1536
                    index: true
                    similarity: cosine
