hwi_oauth:
    connect:
        account_connector: App\Security\OAuthConnector
        registration_form: App\Form\RegistrationFormType
        registration_form_handler: App\Security\FormHandler

    # https://github.com/hwi/HWIOAuthBundle/blob/master/docs/2-configuring_resource_owners.md
    resource_owners:
        github:
            type:                github
            client_id:           Iv23ligtmVJ3fPurxb4y
            client_secret:       b887a28bc85d48148a785403546082828000acdb
            scope:               'user:email'
