services:
    php:
        build:
            context: .
            dockerfile: Dockerfile
            # No target specified to use the final stage (production build)
        environment:
            APP_ENV: prod
            PHP_XDEBUG_ENABLED: "1"
            PHP_IDE_CONFIG: "serverName=app"
        ports:
            - "8000:80"
        extra_hosts:
            - host.docker.internal:host-gateway
        volumes:
            - ./var/log/:/htdocs/var/log/
            - ./.env.local:/htdocs/.env.local
        depends_on:
            - mysql

    mysql:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: app
            MYSQL_USER: app
            MYSQL_PASSWORD: app
        ports:
            - "3306:3306"
        volumes:
            - ./docker/mysql_data:/var/lib/mysql

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.8.0
        environment:
            - discovery.type=single-node
            - xpack.security.enabled=false
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        volumes:
            - elasticsearch-data:/usr/share/elasticsearch/data
        restart: unless-stopped
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:9200"]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 30s

    kibana:
        image: docker.elastic.co/kibana/kibana:8.8.0
        environment:
            - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
        ports:
            - "5601:5601"
        depends_on:
            - elasticsearch
        restart: unless-stopped
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:5601/api/status"]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 60s

volumes:
    elasticsearch-data:
    mysql-data-prod:
