services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    environment:
        PHP_XDEBUG_ENABLED: "1"
        PHP_IDE_CONFIG: "serverName=app"
    volumes:
      - ./:/htdocs
    ports:
      - "8000:80"
