name: Deploy to Production

on:
  push:
    branches:
      - main  # or master, depending on your default branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: snapcomponents.com
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT || 22 }}
          script: |
            cd snapcomponents
            git pull
            docker compose -f compose.prod.yml build php
            docker compose -f compose.prod.yml down php
            docker compose -f compose.prod.yml up php -d
