name: Validate Code

on:
  push:
    branches:
      - main # or master, depending on your default branch name
  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, intl
          coverage: none

      - name: Install PHP dependencies
        run: composer install --prefer-dist --no-progress

      - name: Check PHP code style
        run: composer cs-check

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Node.js dependencies
        run: npm ci

      - name: Validate package.json format
        run: |
          # Check if package.json is valid JSON
          node -e "JSON.parse(require('fs').readFileSync('package.json'))"
          # Check if npm can parse the dependencies correctly
          npm ls --json >/dev/null

      - name: Lint JavaScript/TypeScript code
        run: npm run lint

      - name: Check JavaScript/TypeScript formatting
        run: npm run format
